name: Deploy to EC2 using SSM

on:
  # Manual trigger for the workflow
  workflow_dispatch:
    inputs:
      instanceTag:
        description: 'Tag of the EC2 instance to run the command on'
        required: true
        default: 'MyInstance'
      ssmCommand:
        description: 'Commands to be executed on the EC2 instance'
        required: true
        default: 'echo "Hello World"'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Send command with SSM
        id: run-ssm-command
        run: |
          instance_ids=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${{ github.event.inputs.instanceTag }}" --query "Reservations[*].Instances[*].InstanceId" --output text)
          
          if [ -z "$instance_ids" ]; then
            echo "No instances found with tag: ${{ github.event.inputs.instanceTag }}"
            exit 1
          fi

          commands=$(printf %s "${{ github.event.inputs.ssmCommand }}" | jq -R -s -c 'split("\n")')

          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=$instance_ids" \
            --parameters '{"commands":'"$commands"',"executionTimeout":["3600"]}' \
            --timeout-seconds 600 \
            --comment "Run provided commands"
