name: AWS SSM Send-Command Example

on:
  workflow_dispatch:
    inputs:
      instanceId:
        description: 'ID of the EC2 instance'
        required: true
      installCommands:
        description: 'Commands to run (Separate different commands with a semicolon; and for multiline use | support)'
        required: true
        default: |
          ls -al;
          echo "Deploying application";
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -;
          sudo apt-get install -y nodejs

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ github.event.inputs.instanceId }}
          command: |
            ${{ github.event.inputs.installCommands }}
          comment: "Executing deployment commands"

      - name: Get the Command ID
        run: echo "The Command ID is ${{ steps.ssm.outputs.command-id }}"

      - name: Wait for Command to Complete
        id: wait_for_command
        run: |
          command_id=${{ steps.ssm.outputs.command-id }}
          aws ssm wait command-executed --command-id $command_id --instance-id ${{ github.event.inputs.instanceId }} --region ${{ secrets.AWS_REGION }}          
          echo "Command $command_id executed successfully."

      - name: Check Command Status
        id: check_status
        run: |
          command_id=${{ steps.ssm.outputs.command-id }}
          result=$(aws ssm list-command-invocations --command-id $command_id --details --region ${{ secrets.AWS_REGION }})
          echo "$result"
          status=$(echo $result | jq -r '.CommandInvocations[0].Status')
          output=$(echo $result | jq -r '.CommandInvocations[0].CommandPlugins[0].Output')
          echo "Command Status: $status"
          echo "Command Output: $output"

      - name: Display Command Output
        run: |
          echo "The Command Output is: ${{ steps.check_status.outputs.command-output }}"
