name: AWS SSM Send-Command Example

on:
  workflow_dispatch:
    inputs:
      instanceId:
        description: 'ID of the EC2 instance'
        required: true
      installCommands:
        description: 'Commands to run'
        required: true
        default: echo "Hello World"

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Send Command via AWS SSM
        id: send-command
        run: |
          COMMAND=$(echo "${{ github.event.inputs.installCommands }}")
          RESPONSE=$(aws ssm send-command \
            --instance-ids ${{ github.event.inputs.instanceId }} \
            --document-name "AWS-RunShellScript" \
            --comment "Running specified commands" \
            --parameters commands=["$COMMAND"] \
            --cloud-watch-output-config '{"CloudWatchOutputEnabled":true,"CloudWatchLogGroupName":"SSM-Logs"}' \
            --region ${{ secrets.AWS_REGION }})
          echo "COMMAND_ID=$(echo $RESPONSE | jq -r '.Command.CommandId')" >> $GITHUB_ENV

      - name: Wait for Command Completion
        id: wait-for-completion
        run: |
          aws ssm wait command-executed \
            --command-id ${{ env.COMMAND_ID }} \
            --instance-id ${{ github.event.inputs.instanceId }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Fetch Command Status and Output
        id: fetch-status-output
        run: |
          COMMAND_ID=${{ env.COMMAND_ID }}
          COMMAND_STATUS=$(aws ssm list-command-invocations --command-id $COMMAND_ID --instance-id ${{ github.event.inputs.instanceId }} --query 'CommandInvocations[0].Status' --output text --region ${{ secrets.AWS_REGION }})
          # Get the command output and remove newline characters
          COMMAND_OUTPUT=$(aws ssm get-command-invocation --command-id $COMMAND_ID --instance-id ${{ github.event.inputs.instanceId }} --query 'StandardOutputContent' --output text --region ${{ secrets.AWS_REGION }} | tr -d '\n')
          echo "Command ID: $COMMAND_ID"
          echo "Command Status: $COMMAND_STATUS"
          echo "Command Output: $COMMAND_OUTPUT"
          echo "COMMAND_STATUS=$COMMAND_STATUS" >> $GITHUB_ENV
          echo "COMMAND_OUTPUT=$COMMAND_OUTPUT" >> $GITHUB_ENV

      - name: Print Status
        run: echo "The command execution status is ${{ env.COMMAND_STATUS }}"

      - name: Print Output
        run: echo "The command output is ${{ env.COMMAND_OUTPUT }}"

      - name: Verify Command Execution
        if: env.COMMAND_STATUS != 'Success'
        run: |
          echo "Command did not execute successfully. Status: ${{ env.COMMAND_STATUS }}"
          exit 1
