name: AWS SSM Send-Command Example

on:
  workflow_dispatch:
    inputs:
      instanceId:
        description: 'ID of the EC2 instance'
        required: true
      installCommands:
        description: 'Commands to run (Separate multiple commands with semicolons ";")'
        required: true
        default: |
          ls -al;
          echo "Hello World";
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -;
          sudo apt-get install -y nodejs

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ github.event.inputs.instanceId }}
          working-directory: /home/ubuntu/application
          command: |
            ${{ github.event.inputs.installCommands }}
          comment: "Running specified commands"

      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
