name: AWS SSM Send-Command Example

on:
  workflow_dispatch:
    inputs:
      instanceId:
        description: 'ID of the EC2 instance'
        required: true
      installCommands:
        description: 'Commands to run (Separate different commands with a semicolon; and for multiline use | support)'
        required: true
        default: |
          ls -al;
          echo "Deploying application";
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -;
          sudo apt-get install -y nodejs

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ github.event.inputs.instanceId }}
          command: |
            ${{ github.event.inputs.installCommands }}
          comment: "Executing deployment commands"

      # Catch SSM outputs
      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
